extends: stylelint-config-htmlacademy
customSyntax: postcss-scss
rules:
  indentation: tab
  at-rule-no-unknown: 
    - true
    - ignoreAtRules:
      - mixin
      - define-mixin
      - include
      - content
      - rules
      - each
      - use
